### ISSUE TITLE
Misspelt stored proc call

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#2]
When logged in as a manager and going to "View My Employees" the table comes up empty for EID 1007 (which should not be the case). Below is the console error output:
`Error: ER_SP_DOES_NOT_EXIST: PROCEDURE work_it.ManangeEmployees does not exist
    ....... {
  code: 'ER_SP_DOES_NOT_EXIST',
  errno: 1305,
  sqlMessage: 'PROCEDURE work_it.ManangeEmployees does not exist',
  sqlState: '42000',
  index: 0,
  sql: 'CALL ManangeEmployees(1007)'`

The sql call is for ManangeEmployees, not ManageEmployees. I couldn't find in the code where this was being called with the incorrect name.

**Comment by teddykalp** [comment]
It looks like you need that ManageEmployee Stored Proc

**Comment by teddykalp** [comment]
and also make sure have the Manages table as well

**Comment by stephenDiosDev** [comment]
I already have both the ManageEmployees stored proc and the Manages table in mysql

**Comment by teddykalp** [comment]
Yeah you're right it was a typo on the server end. I just made the change, try it now

**Comment by stephenDiosDev** [comment]
That fixed it, thanks
