### ISSUE TITLE
Text fields/options do not clear when closing the prompt

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#3]
If you log in as a manager (I used 1007), go to **View My Employees**, then go to **Add Employee**, if you fill in information into any of the fields and then close the prompt and reopen it, the information entered will still be there.

It's not so much of a bug if we want to keep it as a quality of life thing, but I figured I would mention it.

**Comment by teddykalp** [comment]
Should work now, please try again

**Comment by stephenDiosDev** [comment]
Fixed
