### ISSUE TITLE
Bad status message after deleting manager schedule entry

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#4]
If you are logged in as a manager and are on the **My Schedule** page and you delete one of your schedule entries, the entry is removed from the screen but right above the table the message _Something went wrong_ is in red.

I'm unsure if this is because the functionality hasn't been fully implemented yet, but figured I'd write it down for later

**Comment by teddykalp** [comment]
Is there an error showing up on the console?

**Comment by stephenDiosDev** [comment]
No, the only thing that shows is "Deleted the schedule" followed by the schedule ID. Everything deletes fine (until I refresh), but the red error message on the webpage pops up (probably by accident)

**Comment by teddykalp** [comment]
I can't seem to recreate the issue, can you try to recreate this issue again?

**Comment by stephenDiosDev** [comment]
When I go to My Schedule as a manager and delete a schedule entry, the console confirms the deletion, the entry disappears but for whatever reason I get _"Something went wrong"_ written in red appearing right under the work it logo. 

Looking through scheduleManager.js, it looks like it comes from the else block of the deleteSchedule function. Looking through mysql, I don't have any stored proc for delete schedule, and there is also no stored proc for delete schedule on the google doc. My guess is that the lack of a stored proc on my end is causing the error, unless we don't need a stored proc for that?

**Comment by teddykalp** [comment]
Yeah we do, sorry that's my bad, just added to the doc. It was the last sql function I built and guess I just forgot to put it in

**Comment by stephenDiosDev** [comment]
Fixed with stored proc
