### ISSUE TITLE
Issue with adding employee as a manager

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#6]
When I log in as a manager (emp 1007) and I go to "View My Employees" and then try to add a new employee, the new employee does not appear in the list. I have the stored proc in mysql. The console output in vscode is this:

_**1007
What is happening
Sent the following data to client
[
  [
    RowDataPacket {
      EID: 1941,
      First_Name: 'Salvador',
      Last_Name: 'Smith',
      Email: 'Salvador.Purinton@gmail.com',
      Phone: '(403)-457-5092',
      Dept_Num: 103
    },
    RowDataPacket {
      EID: 2225,
      First_Name: 'Kathryn',
      Last_Name: 'Andres',
      Email: 'Kathryn.Andres@gmail.com',
      Phone: '(403)-461-5503',
      Dept_Num: 103
    }
  ],
  OkPacket {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0
  }
]**_

and the console output in the browser is this:

GET http://localhost:3000/favicon.ico
[HTTP/1.1 404 Not Found 2ms]

downloadable font: gasp: Changed the version number to 1 (font-family: "Oldenburg" style:normal weight:400 stretch:100 src index:0) source: https://fonts.gstatic.com/s/oldenburg/v10/fC1jPY5JYWzbywv7c4VKVkSp.woff2

Avery
1007
Getting data

I'm not sure if its caused by that 404 error on my end

**Comment by teddykalp** [comment]
Does it refresh the page, when you add the employee. Here's some thoughts a possible fix on your end
1. Pull the latest version of the code
2. Go into the server.js file, the add employee function on line 157
3. Do like a console.log("Something something") and see if its calling the server function

**Comment by teddykalp** [comment]
The console on the browser should be getting back a JSON object like the following
{
       "Message": "success"
}

or 

{
       "Message": "error"
}

Because the other server functionalities are working after that error, this one should work as well

**Comment by stephenDiosDev** [comment]
My issue was with firefox. Chrome processes it perfectly, firefox has issues.
