### ISSUE TITLE
Login clock in/clock out error

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#7]
When I log in as a manager (in this case, eid is 1000), I immediately get this error in my local console  

code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'Clock_in' in 'where clause'",
  sqlState: '42S22',
  index: 0,
  sql: "SELECT * FROM work_it.Clock WHERE EID = 1000 AND Clock_in <> '' AND Clock_out = ''"

Additionally, when I create a schedule where the manager would be working, when I click the Clock in button, I get this console error:
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'Clock_out' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: 'CALL ClockOut(19906, "12:1 AM")'

**Comment by teddykalp** [comment]
Hmm, can you send me a screenshot of your Clock table, we may have different looking tables

**Comment by teddykalp** [comment]
You've also found another bug, that if the minutes are less than 10, it will remove the 0

**Comment by teddykalp** [comment]
I know what the problem is, you have clock_in and clock_out set as datetimes, set them to varchar instead. WIll need to update in the sql file as well

**Comment by teddykalp** [comment]
that's my bad, I forgot to update in the doc when I made the table

**Comment by stephenDiosDev** [comment]
I also noticed that in the table, it is Check_in and Check_out, while the query error specified looking for Clock_in and Clock_out. Changing the table names to match this eliminated this error. However I now have a new error when clicking the Clock In button. It produces this output:

  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: "Incorrect integer value: '' for column 'EID' at row 1",
  sqlState: 'HY000',
  index: 0,
  sql: 'CALL ClockIn(19906, 1000, "12:33 AM", "")'

**Comment by teddykalp** [comment]
do we have it as check in and check out in the doc?

**Comment by stephenDiosDev** [comment]
Using the new table creation script and the newest pull, it works and correctly throws an error if I go Clock in --> Clock out --> Clock in to let me know I have already clocked in and out
