### ISSUE TITLE
Newly added schedule not showing up immediately

### ISSUE THREAD

**Issue by stephenDiosDev** [teddykalp/CPSC471-Project#8]
When I add a new schedule, it will not be added visually to the webpage until I refresh. Is there any way to force the refresh? It's not a big deal, but it will probably need to be mentioned during the project presentation during the website walk through

**Comment by teddykalp** [comment]
Yeah I can fix that rn, I wanted the message to show that the schedule was added successfully before the user refreshed the page. I will just refresh the page automatically once the user has added a schedule

**Comment by stephenDiosDev** [comment]
Perfect, sounds good!
